### PR TITLE
[RFC: 0005]: Functions with containers

### PR DESCRIPTION
**Pull request by kiwicopple**
[Rendered](https://github.com/supabase/rfcs/blob/rfc/functions_with_containers/rfc/0005-functions_with_containers.md)

Demo video

https://user-images.githubusercontent.com/10214025/144591756-f508efbf-cc21-4208-84f5-5a3ca9e7d6e6.mp4

### CODE REVIEW

**Comment by kiwicopple** [comment]
Assets:

Demo v1: https://user-images.githubusercontent.com/10214025/144585545-f49609f0-86b7-4e0b-b796-4768b6a41750.mp4

**Comment by johnhenry** [comment]
Has there been any discussion on the environment format?
It appears that this example uses request-style handlers. It's worth it to consider [Worker Environments](https://workers.js.org/) as well.

**Comment by milanvanschaik** [comment]
Quick note on deploying:
Might be a good idea to use something like [Firecracker](https://firecracker-microvm.github.io/) which ensures isolation between containers. This way it's possible to deploy cost-efficient to the Edge. [Ignite](https://github.com/weaveworks/ignite) might make it even easier by having a Kubernetes cluster with nodes in multiple zones/regions.

**Comment by swamidass** [comment]
Being able to run functions in containers would be a killer feature for our use case in the sciences.

Is there an ETA or alpha we play with this?

**Comment by swamidass** [comment]
To be clear, ideally being able to run in arbitrary docker containers is what would be most helpful.

**Comment by kiwicopple** [comment]
closing this since we now have Edge Functions: https://supabase.com/docs/guides/functions

**Pull request closed without merging**
